var data = {
  Andhra_Pradesh: "Amaravati",
  Arunachal_Pradesh: "Itanagar",
  Assam: "Dispur",
  Bihar: "Patna",
  Chhattisgarh: "Raipur",
  Goa: "Panaji",
  Gujarat: "Gandhinagar",
  Haryana: "Chandigarh",
  Himachal_Pradesh: "Shimla",
  JK: "Srinagar (Summer), Jammu (Winter)",
  Jharkhand: "Ranchi",
  Karnataka: "Bengaluru",
  Kerala: "Thiruvananthapuram",
  Madhya_Pradesh: "Bhopal",
  Maharashtra: "Mumbai",
  Manipur: "Imphal",
  Meghalaya: "Shillong",
  Mizoram: "Aizawl",
  Nagaland: "Kohima",
  Odisha: "Bhubaneswar",
  Punjab: "Chandigarh",
  Rajasthan: "Jaipur",
  Sikkim: "Gangtok",
  Tamil_Nadu: "Chennai",
  Telangana: "Hyderabad",
  Tripura: "Agartala",
  Uttar_Pradesh: "Lucknow",
  Uttarakhand: "Dehradun",
  West_Bengal: "Kolkata"
}
